# Generated by Django 6.0 on 2025-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
